webtalk_init -webtalk_dir C:/Users/k/Dev/Projects/PRESENT_Cipher_Verilog/encrypt/encrypt.sim/sim_1/behav/xsim/xsim.dir/encrypt_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jun 26 18:16:35 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e9a8e46a-46cc-424d-9a4a-3c03bb495001" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "acc92a7da9f446fb9ee95428e6a9709c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "78" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 2600 Six-Core Processor            " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "6" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "95 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "6 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "96" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "6" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.55_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "62136_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2758564726 -regid "" -xml C:/Users/k/Dev/Projects/PRESENT_Cipher_Verilog/encrypt/encrypt.sim/sim_1/behav/xsim/xsim.dir/encrypt_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/k/Dev/Projects/PRESENT_Cipher_Verilog/encrypt/encrypt.sim/sim_1/behav/xsim/xsim.dir/encrypt_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/k/Dev/Projects/PRESENT_Cipher_Verilog/encrypt/encrypt.sim/sim_1/behav/xsim/xsim.dir/encrypt_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
