# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Basys3_Master.xdc

# IP: ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: c:/Users/k/Dev/Projects/PRESENT_Cipher_Verilog/encrypt/encrypt.gen/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc

# XDC: c:/Users/k/Dev/Projects/PRESENT_Cipher_Verilog/encrypt/encrypt.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
